//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiHQT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configurate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configurate()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ConfigurateID { get; set; }
        public string Display { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string GraphicsChip { get; set; }
        public string HDD { get; set; }
        public string SSD { get; set; }
        public string HDMI { get; set; }
        public string VGA { get; set; }
        public string Keyboard { get; set; }
        public string OperatingSystem { get; set; }
        public string Size { get; set; }
        public string Battery { get; set; }
        public string Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
