//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiHQT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CuoiKi_HQTCSDLEntities : DbContext
    {
        public CuoiKi_HQTCSDLEntities()
            : base("name=CuoiKi_HQTCSDLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giay> Giays { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<HangGiay> HangGiays { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<ViewGiay> ViewGiays { get; set; }
        public virtual DbSet<ViewHangGiay> ViewHangGiays { get; set; }
        public virtual DbSet<ViewKhacHang> ViewKhacHangs { get; set; }
        public virtual DbSet<ViewKho> ViewKhoes { get; set; }
        public virtual DbSet<ViewLSGD> ViewLSGDs { get; set; }
        public virtual DbSet<ViewSale> ViewSales { get; set; }
        public virtual DbSet<ViewTheLoai> ViewTheLoais { get; set; }
        public virtual DbSet<ViewGioHang1> ViewGioHang1 { get; set; }
    
        [DbFunction("CuoiKi_HQTCSDLEntities", "SPSale")]
        public virtual IQueryable<SPSale_Result> SPSale()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SPSale_Result>("[CuoiKi_HQTCSDLEntities].[SPSale]()");
        }
    
        public virtual ObjectResult<LietKeGiayBanChay_Result> LietKeGiayBanChay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LietKeGiayBanChay_Result>("LietKeGiayBanChay");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [DbFunction("CuoiKi_HQTCSDLEntities", "SanPhamGiamGia")]
        public virtual IQueryable<SanPhamGiamGia_Result> SanPhamGiamGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SanPhamGiamGia_Result>("[CuoiKi_HQTCSDLEntities].[SanPhamGiamGia]()");
        }
    
        public virtual int AddHangGiay(string tenhang)
        {
            var tenhangParameter = tenhang != null ?
                new ObjectParameter("tenhang", tenhang) :
                new ObjectParameter("tenhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHangGiay", tenhangParameter);
        }
    
        [DbFunction("CuoiKi_HQTCSDLEntities", "ChiTietSanPham")]
        public virtual IQueryable<ChiTietSanPham_Result> ChiTietSanPham(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChiTietSanPham_Result>("[CuoiKi_HQTCSDLEntities].[ChiTietSanPham](@id)", idParameter);
        }
    
        public virtual int TaoTaiKhoan(string tendn, string tenKH, string matKhau, string email, string sdt, string diaChi, Nullable<bool> isAdmin)
        {
            var tendnParameter = tendn != null ?
                new ObjectParameter("Tendn", tendn) :
                new ObjectParameter("Tendn", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaoTaiKhoan", tendnParameter, tenKHParameter, matKhauParameter, emailParameter, sdtParameter, diaChiParameter, isAdminParameter);
        }
    
        public virtual int SuaSoLuongDH(Nullable<int> id, Nullable<int> soluong, Nullable<decimal> giatridon)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var giatridonParameter = giatridon.HasValue ?
                new ObjectParameter("giatridon", giatridon) :
                new ObjectParameter("giatridon", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaSoLuongDH", idParameter, soluongParameter, giatridonParameter);
        }
    
        public virtual int XoaKhoiGioHang(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaKhoiGioHang", idParameter);
        }
    
        public virtual int AddGioHang(Nullable<decimal> giatridon, string tendn, Nullable<int> magiay, Nullable<int> size, Nullable<int> soluong)
        {
            var giatridonParameter = giatridon.HasValue ?
                new ObjectParameter("giatridon", giatridon) :
                new ObjectParameter("giatridon", typeof(decimal));
    
            var tendnParameter = tendn != null ?
                new ObjectParameter("tendn", tendn) :
                new ObjectParameter("tendn", typeof(string));
    
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddGioHang", giatridonParameter, tendnParameter, magiayParameter, sizeParameter, soluongParameter);
        }
    
        public virtual int Giay_D(Nullable<int> magiay)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Giay_D", magiayParameter);
        }
    
        public virtual int Giay_I(Nullable<int> magiay, string tengiay, Nullable<decimal> gia, Nullable<int> mahang, Nullable<int> matheloai, Nullable<int> masale, string hinhanh)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            var tengiayParameter = tengiay != null ?
                new ObjectParameter("tengiay", tengiay) :
                new ObjectParameter("tengiay", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Giay_I", magiayParameter, tengiayParameter, giaParameter, mahangParameter, matheloaiParameter, masaleParameter, hinhanhParameter);
        }
    
        public virtual ObjectResult<Giay_S_Result> Giay_S()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Giay_S_Result>("Giay_S");
        }
    
        public virtual ObjectResult<Giay_SD_Result> Giay_SD(Nullable<int> magiay)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Giay_SD_Result>("Giay_SD", magiayParameter);
        }
    
        public virtual int HangGiay_D(Nullable<int> mahang)
        {
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HangGiay_D", mahangParameter);
        }
    
        public virtual int HangGiay_I(Nullable<int> mahang, string tenhang)
        {
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            var tenhangParameter = tenhang != null ?
                new ObjectParameter("tenhang", tenhang) :
                new ObjectParameter("tenhang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HangGiay_I", mahangParameter, tenhangParameter);
        }
    
        public virtual ObjectResult<HangGiay_S_Result> HangGiay_S()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HangGiay_S_Result>("HangGiay_S");
        }
    
        public virtual ObjectResult<HangGiay_SD_Result> HangGiay_SD(Nullable<int> mahang)
        {
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HangGiay_SD_Result>("HangGiay_SD", mahangParameter);
        }
    
        public virtual int HangGiay_U(string tenhang, Nullable<int> mahang)
        {
            var tenhangParameter = tenhang != null ?
                new ObjectParameter("tenhang", tenhang) :
                new ObjectParameter("tenhang", typeof(string));
    
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HangGiay_U", tenhangParameter, mahangParameter);
        }
    
        public virtual int Kho_D(Nullable<int> magiay)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Kho_D", magiayParameter);
        }
    
        public virtual int Kho_I(Nullable<int> magiay, Nullable<int> size, Nullable<int> soluong)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Kho_I", magiayParameter, sizeParameter, soluongParameter);
        }
    
        public virtual ObjectResult<Kho_S_Result> Kho_S()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kho_S_Result>("Kho_S");
        }
    
        public virtual ObjectResult<Kho_SD_Result> Kho_SD(Nullable<int> magiay)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Kho_SD_Result>("Kho_SD", magiayParameter);
        }
    
        public virtual int Kho_U(Nullable<int> size, Nullable<int> soluong, Nullable<int> magiay)
        {
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Kho_U", sizeParameter, soluongParameter, magiayParameter);
        }
    
        public virtual int Sale_D(Nullable<int> masale)
        {
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sale_D", masaleParameter);
        }
    
        public virtual int Sale_I(Nullable<int> masale, Nullable<int> ptsale, Nullable<System.DateTime> bD, Nullable<System.DateTime> kT)
        {
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            var ptsaleParameter = ptsale.HasValue ?
                new ObjectParameter("ptsale", ptsale) :
                new ObjectParameter("ptsale", typeof(int));
    
            var bDParameter = bD.HasValue ?
                new ObjectParameter("BD", bD) :
                new ObjectParameter("BD", typeof(System.DateTime));
    
            var kTParameter = kT.HasValue ?
                new ObjectParameter("KT", kT) :
                new ObjectParameter("KT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sale_I", masaleParameter, ptsaleParameter, bDParameter, kTParameter);
        }
    
        public virtual ObjectResult<Sale_S_Result> Sale_S()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_S_Result>("Sale_S");
        }
    
        public virtual ObjectResult<Sale_SId_Result> Sale_SId(Nullable<int> masale)
        {
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_SId_Result>("Sale_SId", masaleParameter);
        }
    
        public virtual int Sale_U(Nullable<int> masale, Nullable<int> ptsale, Nullable<System.DateTime> bD, Nullable<System.DateTime> kT)
        {
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            var ptsaleParameter = ptsale.HasValue ?
                new ObjectParameter("ptsale", ptsale) :
                new ObjectParameter("ptsale", typeof(int));
    
            var bDParameter = bD.HasValue ?
                new ObjectParameter("BD", bD) :
                new ObjectParameter("BD", typeof(System.DateTime));
    
            var kTParameter = kT.HasValue ?
                new ObjectParameter("KT", kT) :
                new ObjectParameter("KT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sale_U", masaleParameter, ptsaleParameter, bDParameter, kTParameter);
        }
    
        public virtual int TheLoai_D(Nullable<int> matheloai)
        {
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TheLoai_D", matheloaiParameter);
        }
    
        public virtual int TheLoai_I(Nullable<int> matheloai, string tentheloai)
        {
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            var tentheloaiParameter = tentheloai != null ?
                new ObjectParameter("tentheloai", tentheloai) :
                new ObjectParameter("tentheloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TheLoai_I", matheloaiParameter, tentheloaiParameter);
        }
    
        public virtual ObjectResult<TheLoai_S_Result> TheLoai_S()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TheLoai_S_Result>("TheLoai_S");
        }
    
        public virtual ObjectResult<TheLoai_SD_Result> TheLoai_SD(Nullable<int> matheloai)
        {
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TheLoai_SD_Result>("TheLoai_SD", matheloaiParameter);
        }
    
        public virtual int TheLoai_U(Nullable<int> matheloai, string tentheloai)
        {
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            var tentheloaiParameter = tentheloai != null ?
                new ObjectParameter("tentheloai", tentheloai) :
                new ObjectParameter("tentheloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TheLoai_U", matheloaiParameter, tentheloaiParameter);
        }
    
        public virtual int AddLichSuGiaoDich(string tendn, Nullable<decimal> giatri, Nullable<int> magiay, Nullable<int> size, Nullable<int> soluong, Nullable<System.DateTime> thoigian)
        {
            var tendnParameter = tendn != null ?
                new ObjectParameter("tendn", tendn) :
                new ObjectParameter("tendn", typeof(string));
    
            var giatriParameter = giatri.HasValue ?
                new ObjectParameter("giatri", giatri) :
                new ObjectParameter("giatri", typeof(decimal));
    
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thoigianParameter = thoigian.HasValue ?
                new ObjectParameter("thoigian", thoigian) :
                new ObjectParameter("thoigian", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLichSuGiaoDich", tendnParameter, giatriParameter, magiayParameter, sizeParameter, soluongParameter, thoigianParameter);
        }
    
        public virtual int Giay_U(Nullable<int> magiay, string tengiay, Nullable<decimal> gia, Nullable<int> mahang, Nullable<int> matheloai, Nullable<int> masale, string hinhanh)
        {
            var magiayParameter = magiay.HasValue ?
                new ObjectParameter("magiay", magiay) :
                new ObjectParameter("magiay", typeof(int));
    
            var tengiayParameter = tengiay != null ?
                new ObjectParameter("tengiay", tengiay) :
                new ObjectParameter("tengiay", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var mahangParameter = mahang.HasValue ?
                new ObjectParameter("mahang", mahang) :
                new ObjectParameter("mahang", typeof(int));
    
            var matheloaiParameter = matheloai.HasValue ?
                new ObjectParameter("matheloai", matheloai) :
                new ObjectParameter("matheloai", typeof(int));
    
            var masaleParameter = masale.HasValue ?
                new ObjectParameter("masale", masale) :
                new ObjectParameter("masale", typeof(int));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Giay_U", magiayParameter, tengiayParameter, giaParameter, mahangParameter, matheloaiParameter, masaleParameter, hinhanhParameter);
        }
    
        public virtual int TaoTk(string tendn, string tenKH, string matKhau, string email, string sdt, string diaChi, Nullable<bool> isAdmin)
        {
            var tendnParameter = tendn != null ?
                new ObjectParameter("Tendn", tendn) :
                new ObjectParameter("Tendn", typeof(string));
    
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("isAdmin", isAdmin) :
                new ObjectParameter("isAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaoTk", tendnParameter, tenKHParameter, matKhauParameter, emailParameter, sdtParameter, diaChiParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<Showsanpham_Result> Showsanpham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Showsanpham_Result>("Showsanpham");
        }
    
        public virtual ObjectResult<Showgiohang_Result> Showgiohang(string tendn)
        {
            var tendnParameter = tendn != null ?
                new ObjectParameter("tendn", tendn) :
                new ObjectParameter("tendn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Showgiohang_Result>("Showgiohang", tendnParameter);
        }
    }
}
