//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiHQT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public int MaGD { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public string TenDN { get; set; }
        public Nullable<int> MaGiay { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
