//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiHQT.Models
{
    using System;
    
    public partial class Showsanpham_Result2
    {
        public int MaGiay { get; set; }
        public string TenGiay { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string HinhAnh { get; set; }
    }
}
