//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiHQT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSale
    {
        public int MaSale { get; set; }
        public Nullable<int> PtSale { get; set; }
        public Nullable<System.DateTime> Tgbd { get; set; }
        public Nullable<System.DateTime> Tgkt { get; set; }
    }
}
